### PR TITLE
Extend XenForo Tagging support

### PR DESCRIPTION
**Pull request by Xon**
XenForo's Redactor editor has special logic to handle copy & pasted user tagging snippets. This pull request adds that support to TinyQuattro

### CODE REVIEW

**Comment by cclaerhout** [comment]
The regex is the original one, but is not correct (it has bugs). I will have a look at it.

**Comment by cclaerhout** [comment]
Bb Code text:
a
[USER=1]technologue[/USER]
b

Once converted, the copy/paste didn't trigger the regex. I've modified this in the last commit.

**Comment by cclaerhout** [comment]
Thanks by the way, I didn't see this feature.

**Comment by Xon** [comment]
@cclaerhout that regex was a copy & paste from XF 1.4.8, so looks like a bug report is needed :)

**Pull request closed without merging**
