### PR TITLE
Replace regex bbcode cleaning with bbcode DOM manipulation

### PR DESCRIPTION
**Pull request by Xon**
Uses the Standard XenForo Parser and a minor custom bbcode formatter to parser & render bbcodes.

A cleanup phase is applied to the bbcode tree which eliminates redundant bbcode before rendering.

### CODE REVIEW

**Comment by Xon** [comment]
Note; this doesn't handle this sort of construct:

```
[font=Times New Roman][b][i]word1[/i][/b][/font] [font=Times New Roman][b][i] word2[/i][/b][/font]
```

I've seen this sort of behaviour when copy & pasting from google docs, and it causes horrible performance with enough of that behaviour. 

I'ld also like to refactor this code so the bbcode cleaning can run when a post is being saved to reduce bbcode complexity (and thus render time)

**Comment by cclaerhout** [comment]
Could you please check if the new preview version is working fine with you :)

**Comment by Xon** [comment]
Will look at it tomorrow :+1:

**Comment by Xon** [comment]
Initially looks appear fine. 

Will need to-do some more in-depth testing this weekend with some known problem posts before rolling this out to Live for final testing.

**Comment by cclaerhout** [comment]
No problem, there's no hurry at all :)

**Comment by Xon** [comment]
Deployed the preview build to Live Sufficient Velocity without any issue so far, looks great :)

:+1:

**Comment by cclaerhout** [comment]
Thanks for your feedback !

**Pull request closed without merging**
